# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x05terms\"\x07\n\x05\x45mpty\">\n\x04Term\x12\r\n\x05title\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x13\n\x0bsource_link\x18\x03 \x01(\t\"5\n\nTermUpdate\x12\x12\n\ndefinition\x18\x01 \x01(\t\x12\x13\n\x0bsource_link\x18\x02 \x01(\t\"p\n\x08TermList\x12)\n\x05terms\x18\x01 \x03(\x0b\x32\x1a.terms.TermList.TermsEntry\x1a\x39\n\nTermsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.terms.Term:\x02\x38\x01\"?\n\x11\x43reateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x19\n\x04term\x18\x02 \x01(\x0b\x32\x0b.terms.Term\"L\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12&\n\x0bterm_update\x18\x02 \x01(\x0b\x32\x11.terms.TermUpdate2\xac\x01\n\x0cTermsService\x12.\n\x0bGetAllTerms\x12\x0c.terms.Empty\x1a\x0f.terms.TermList\"\x00\x12\x35\n\nCreateTerm\x12\x18.terms.CreateTermRequest\x1a\x0b.terms.Term\"\x00\x12\x35\n\nUpdateTerm\x12\x18.terms.UpdateTermRequest\x1a\x0b.terms.Term\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERMLIST_TERMSENTRY']._loaded_options = None
  _globals['_TERMLIST_TERMSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=25
  _globals['_EMPTY']._serialized_end=32
  _globals['_TERM']._serialized_start=34
  _globals['_TERM']._serialized_end=96
  _globals['_TERMUPDATE']._serialized_start=98
  _globals['_TERMUPDATE']._serialized_end=151
  _globals['_TERMLIST']._serialized_start=153
  _globals['_TERMLIST']._serialized_end=265
  _globals['_TERMLIST_TERMSENTRY']._serialized_start=208
  _globals['_TERMLIST_TERMSENTRY']._serialized_end=265
  _globals['_CREATETERMREQUEST']._serialized_start=267
  _globals['_CREATETERMREQUEST']._serialized_end=330
  _globals['_UPDATETERMREQUEST']._serialized_start=332
  _globals['_UPDATETERMREQUEST']._serialized_end=408
  _globals['_TERMSSERVICE']._serialized_start=411
  _globals['_TERMSSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
