# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glossary_pb2 as glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TermsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTerms = channel.unary_unary(
                '/terms.TermsService/GetAllTerms',
                request_serializer=glossary__pb2.Empty.SerializeToString,
                response_deserializer=glossary__pb2.TermList.FromString,
                _registered_method=True)
        self.CreateTerm = channel.unary_unary(
                '/terms.TermsService/CreateTerm',
                request_serializer=glossary__pb2.CreateTermRequest.SerializeToString,
                response_deserializer=glossary__pb2.Term.FromString,
                _registered_method=True)
        self.UpdateTerm = channel.unary_unary(
                '/terms.TermsService/UpdateTerm',
                request_serializer=glossary__pb2.UpdateTermRequest.SerializeToString,
                response_deserializer=glossary__pb2.Term.FromString,
                _registered_method=True)


class TermsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TermsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTerms,
                    request_deserializer=glossary__pb2.Empty.FromString,
                    response_serializer=glossary__pb2.TermList.SerializeToString,
            ),
            'CreateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTerm,
                    request_deserializer=glossary__pb2.CreateTermRequest.FromString,
                    response_serializer=glossary__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=glossary__pb2.UpdateTermRequest.FromString,
                    response_serializer=glossary__pb2.Term.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terms.TermsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terms.TermsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TermsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terms.TermsService/GetAllTerms',
            glossary__pb2.Empty.SerializeToString,
            glossary__pb2.TermList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terms.TermsService/CreateTerm',
            glossary__pb2.CreateTermRequest.SerializeToString,
            glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terms.TermsService/UpdateTerm',
            glossary__pb2.UpdateTermRequest.SerializeToString,
            glossary__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
